# projects_data.py
# Pangaea Advisory ΓÇö Project Master Dataset
# Each property contains:
#   - Frontend display data (image, description, specs, tags etc.)
#   - determinant_scores: 8 normalized scores (0-10 scale) for project engine
#
# Score sources:
#   Greece (Lux&Easy, Lamda): sourced directly from projects_master_data.xlsx
#   UAE (Emaar, Sobha, Damac, Binghatti): sourced from projects_master_data.xlsx
#   Portugal, Thailand: inferred from developer profile + property characteristics
#
# Score scale:
#   project_exit_liquidity:          1-5 (from dataset, 5 = most liquid)
#   expected_rental_yield:           0-10 (yield% as score, e.g. 6.5% = 6.5)
#   public_infrastructure_proximity: 1-5 (from dataset, 5 = best connectivity)
#   financial_strength:              0-10 (from dataset)
#   project_completion_rate:         0-10 (midpoint of range / 10, e.g. 85% = 8.5)
#   construction_quality:            0-10 (text mapped: Very High=10, High=8, Moderate-High=6, Moderate=4)
#   litigation_history:              0-10 INVERSE (8=clean, 6=minor disputes, 4=moderate, 2=material)
#   delivery_history:                0-5  (Extensive=5, Moderate-High=4, Moderate=3, Limited=1)

PROJECTS = {
    # ΓöÇΓöÇΓöÇ PORTUGAL ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

    "the_lisboans": {
        "project_name": "The Lisboans",
        "country": "Portugal",
        "city": "Lisbon",
        "flag": "≡ƒç╡≡ƒç╣",
        "image": "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800",
        "developer": "Oxy Capital",
        "price_range": "Γé¼450K ΓÇô Γé¼2.5M",
        "project_type": "Mixed-use",
        "project_stage": "Ready to Move",
        "ownership": "Freehold",
        "golden_visa": True,
        "rental_yield_display": "5.5% ΓÇô 7%",
        "highlight": "Premium hospitality-lifestyle residences in Lisbon's historic core",
        "description": "The Lisboans is a landmark hospitality-residential concept in Alfama, Lisbon's oldest and most iconic district. Developed by Oxy Capital, the project blends boutique hotel services with private residential ownership, offering investors a rare combination of lifestyle asset and Golden Visa eligibility. Located steps from Pra├ºa do Com├⌐rcio and the Tagus riverfront, residents enjoy 5-star amenities, concierge services, and direct access to Lisbon's most sought-after cultural and dining destinations.",
        "specs": [
            {"label": "Location", "value": "Alfama / Baixa-Chiado, Lisbon"},
            {"label": "Developer", "value": "Oxy Capital"},
            {"label": "Units Available", "value": "15 of 20"},
            {"label": "Completion", "value": "December 2026"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Yes ΓÇö eligible"},
            {"label": "Rental Yield", "value": "5.5% ΓÇô 7% estimated"},
            {"label": "Price Range", "value": "Γé¼450,000 ΓÇô Γé¼2,500,000"},
        ],
        "tags": ["Golden Visa eligible", "Within budget", "Schools & hospitals nearby", "Ready to move in"],
        "score_reasons": [
            "Portugal matches your geographic preference",
            "Golden Visa program satisfies mandatory residency requirement",
            "Ready-to-move suits conservative timeline",
            "Schools and hospitals within walking distance",
        ],
        "determinant_scores": {
            "project_exit_liquidity": 4.0,
            "expected_rental_yield": 6.2,
            "public_infrastructure_proximity": 5.0,
            "financial_strength": 7.0,
            "project_completion_rate": 8.5,
            "construction_quality": 8.0,
            "litigation_history": 7.0,   # INVERSE ΓÇö higher = cleaner record
            "delivery_history": 4.0,
        },
    },

    "palmares": {
        "project_name": "Palmares Ocean Living & Golf Resort",
        "country": "Portugal",
        "city": "Algarve",
        "flag": "≡ƒç╡≡ƒç╣",
        "image": "https://images.unsplash.com/photo-1587502537745-84b86da1204f?w=800",
        "developer": "Oxy Capital",
        "price_range": "Γé¼199K ΓÇô Γé¼1.1M",
        "project_type": "Mixed-use Resort",
        "project_stage": "Under Construction",
        "ownership": "Freehold",
        "golden_visa": True,
        "rental_yield_display": "4% ΓÇô 6%",
        "highlight": "Golf resort residences on the Algarve coast with Golden Visa access",
        "description": "Palmares Ocean Living & Golf Resort occupies a spectacular position on the Algarve coast near Lagos, set within a world-class golf resort overlooking Meia Praia beach and the Alvor estuary. Developed by Oxy Capital, the project offers branded resort residences with full property management, rental pooling, and Golden Visa eligibility. Algarve's status as Europe's premier golf and lifestyle destination makes this a high-conviction hold for families seeking residency with strong leisure upside.",
        "specs": [
            {"label": "Location", "value": "Lagos / Meia Praia, Algarve"},
            {"label": "Developer", "value": "Oxy Capital"},
            {"label": "Units Available", "value": "450 of 500"},
            {"label": "Completion", "value": "June 2027"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Yes ΓÇö eligible"},
            {"label": "Rental Yield", "value": "4% ΓÇô 6% estimated"},
            {"label": "Price Range", "value": "Γé¼199,000 ΓÇô Γé¼1,100,000"},
        ],
        "tags": ["Golden Visa eligible", "Resort lifestyle", "Under construction upside", "Algarve coastal"],
        "score_reasons": [
            "Portugal matches your geographic preference",
            "Golden Visa program satisfies mandatory residency requirement",
            "Resort-managed structure suits family lifestyle",
            "Lowest entry point in the Portuguese Golden Visa market",
        ],
        "determinant_scores": {
            "project_exit_liquidity": 3.0,
            "expected_rental_yield": 5.0,
            "public_infrastructure_proximity": 3.0,
            "financial_strength": 7.0,
            "project_completion_rate": 8.0,
            "construction_quality": 7.0,
            "litigation_history": 7.0,
            "delivery_history": 4.0,
        },
    },

    "amoreiras": {
        "project_name": "Amoreiras Prime Residences",
        "country": "Portugal",
        "city": "Lisbon",
        "flag": "≡ƒç╡≡ƒç╣",
        "image": "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800",
        "developer": "Vanguard Properties",
        "price_range": "Γé¼750K ΓÇô Γé¼3.5M",
        "project_type": "Residential",
        "project_stage": "Ready to Move",
        "ownership": "Freehold",
        "golden_visa": True,
        "rental_yield_display": "4.5% ΓÇô 6%",
        "highlight": "Landmark luxury development in Lisbon's most connected neighbourhood",
        "description": "Amoreiras Prime Residences is a landmark luxury development by Vanguard Properties in the heart of Lisbon's Amoreiras district ΓÇö home to the Amoreiras Shopping Centre, the Lyc├⌐e Fran├ºais Charles Lepierre, and direct access to the Marqu├¬s de Pombal business corridor. With only 34 units across a boutique building, the project offers genuine scarcity value, Golden Visa eligibility, and the Vanguard brand guarantee.",
        "specs": [
            {"label": "Location", "value": "Amoreiras, Lisbon"},
            {"label": "Developer", "value": "Vanguard Properties"},
            {"label": "Units Available", "value": "25 of 34"},
            {"label": "Completion", "value": "December 2026"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Yes ΓÇö eligible"},
            {"label": "Rental Yield", "value": "4.5% ΓÇô 6% estimated"},
            {"label": "Price Range", "value": "Γé¼750,000 ΓÇô Γé¼3,500,000"},
        ],
        "tags": ["Golden Visa eligible", "French school nearby", "Business district access", "Vanguard luxury brand"],
        "score_reasons": [
            "Portugal matches your geographic preference",
            "Golden Visa program satisfies mandatory residency requirement",
            "International school (Lyc├⌐e Fran├ºais) within walking distance",
            "Ready-to-move suits conservative timeline",
        ],
        "determinant_scores": {
            "project_exit_liquidity": 4.0,
            "expected_rental_yield": 5.2,
            "public_infrastructure_proximity": 5.0,
            "financial_strength": 8.0,
            "project_completion_rate": 8.5,
            "construction_quality": 8.0,
            "litigation_history": 8.0,
            "delivery_history": 4.0,
        },
    },

    "infante": {
        "project_name": "Infante Residences",
        "country": "Portugal",
        "city": "Lisbon",
        "flag": "≡ƒç╡≡ƒç╣",
        "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
        "developer": "Vanguard Properties",
        "price_range": "Γé¼399K ΓÇô Γé¼1.01M",
        "project_type": "Residential",
        "project_stage": "Under Construction",
        "ownership": "Freehold",
        "golden_visa": False,
        "rental_yield_display": "6%",
        "highlight": "Rehabilitation condominium development in Lisbon's central district",
        "description": "Infante Residences is a rehabilitation condominium development located in the Estrela / Avenida Infante Santo area of Lisbon. Developed by Vanguard Properties, the project is situated near Jardim da Estrela, LX Factory, Amoreiras, and Hospital CUF Tejo.",
        "specs": [
            {"label": "Location", "value": "Estrela / Avenida Infante Santo, Lisbon"},
            {"label": "Developer", "value": "Vanguard Properties"},
            {"label": "Units Available", "value": "41 of 45"},
            {"label": "Completion", "value": "September 2026"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Not applicable"},
            {"label": "Rental Yield", "value": "6% estimated"},
            {"label": "Price Range", "value": "Γé¼399,000 ΓÇô Γé¼1,015,000"},
        ],
        "tags": ["Central location", "Rehabilitation project", "Hospitals nearby"],
        "score_reasons": [
            "Portugal matches geographic preference",
            "Central access to public transit and embassies",
            "Established developer track record",
        ],
        "determinant_scores": {
            "project_exit_liquidity": 3.0,
            "expected_rental_yield": 6.0,
            "public_infrastructure_proximity": 4.0,
            "financial_strength": 8.0,
            "project_completion_rate": 8.5,
            "construction_quality": 7.0,
            "litigation_history": 8.0,
            "delivery_history": 4.0,
        },
    },

    # ΓöÇΓöÇΓöÇ GREECE ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

    "luxeasy": {
        "project_name": "LUX&EASY Thessaloniki",
        "country": "Greece",
        "city": "Thessaloniki",
        "flag": "≡ƒç¼≡ƒç╖",
        "image": "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=800",
        "developer": "NOVA CONSTRUCTIONS S.A.",
        "price_range": "Γé¼120K ΓÇô Γé¼240K",
        "project_type": "Residential",
        "project_stage": "Under Construction",
        "ownership": "Freehold",
        "golden_visa": True,
        "rental_yield_display": "5% ΓÇô 6.5%",
        "highlight": "High-volume branded residences with strong Greek Golden Visa pathway",
        "description": "LUX&EASY Thessaloniki is a large-scale branded residential development by NOVA CONSTRUCTIONS S.A. in Greece's second-largest city. With over 2,300 units across the Thessaloniki Metropolitan Area, the project offers the lowest entry point into the Greek Golden Visa program at Γé¼120,000 ΓÇö well below Athens pricing.",
        "specs": [
            {"label": "Location", "value": "Thessaloniki Metropolitan Area, Greece"},
            {"label": "Developer", "value": "NOVA CONSTRUCTIONS S.A."},
            {"label": "Units Available", "value": "2,141 of 2,300"},
            {"label": "Completion", "value": "March 2027"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Yes ΓÇö eligible from Γé¼120K"},
            {"label": "Rental Yield", "value": "5% ΓÇô 6.5% estimated"},
            {"label": "Price Range", "value": "Γé¼120,000 ΓÇô Γé¼240,000"},
        ],
        "tags": ["Golden Visa eligible", "Lowest entry point", "Central urban location", "Family infrastructure nearby"],
        "score_reasons": [
            "Greece matches your geographic preference",
            "Golden Visa program satisfies mandatory residency requirement",
            "Lowest entry point in EU Golden Visa market",
            "Urban infrastructure with schools and hospitals nearby",
        ],
        # Inferred from NOVA CONSTRUCTIONS profile (ISO certified, KPMG audited)
        "determinant_scores": {
            "project_exit_liquidity": 3.0,
            "expected_rental_yield": 5.8,
            "public_infrastructure_proximity": 3.0,
            "financial_strength": 6.0,
            "project_completion_rate": 8.5,
            "construction_quality": 6.0,
            "litigation_history": 6.0,
            "delivery_history": 4.0,
        },
    },

    "one_athens": {
        "project_name": "One Athens",
        "country": "Greece",
        "city": "Athens",
        "flag": "≡ƒç¼≡ƒç╖",
        "image": "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800",
        "developer": "DIMAND",
        "price_range": "Γé¼200K ΓÇô Γé¼4.5M",
        "project_type": "Residential",
        "project_stage": "Ready to Move",
        "ownership": "Freehold",
        "golden_visa": False,
        "rental_yield_display": "5.2%",
        "highlight": "Ready-to-move residential redevelopment in central Athens",
        "description": "One Athens is a residential redevelopment project delivered by DIMAND. Located in Kolonaki / Athens City Centre, it offers central proximity to the Athens Concert Hall, embassies, luxury retail, and museums.",
        "specs": [
            {"label": "Location", "value": "Kolonaki / Athens City Centre, Athens"},
            {"label": "Developer", "value": "DIMAND"},
            {"label": "Units Available", "value": "180 of 200"},
            {"label": "Completion", "value": "March 2027"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Not applicable"},
            {"label": "Rental Yield", "value": "5.2% estimated"},
            {"label": "Price Range", "value": "Γé¼200,000 ΓÇô Γé¼4,500,000"},
        ],
        "tags": ["Ready to move in", "City centre", "Luxury retail access"],
        "score_reasons": [
            "Greece matches geographic preference",
            "Ready-to-move status suits immediate timelines",
            "Prime central location near cultural landmarks",
        ],
        "determinant_scores": {
            "project_exit_liquidity": 4.0,
            "expected_rental_yield": 5.2,
            "public_infrastructure_proximity": 5.0,
            "financial_strength": 7.0,
            "project_completion_rate": 9.0,
            "construction_quality": 7.0,
            "litigation_history": 7.0,
            "delivery_history": 4.0,
        },
    },

    "ellinikon": {
        "project_name": "The Ellinikon ΓÇô Marina Residences",
        "country": "Greece",
        "city": "Athens",
        "flag": "≡ƒç¼≡ƒç╖",
        "image": "https://images.unsplash.com/photo-1601918774516-5f5f9d0a6458?w=800",
        "developer": "LAMDA Development",
        "price_range": "Γé¼1M ΓÇô Γé¼20M",
        "project_type": "Residential",
        "project_stage": "Under Construction",
        "ownership": "Freehold",
        "golden_visa": False,
        "rental_yield_display": "5%",
        "highlight": "Luxury waterfront living within Europe's largest urban regeneration project",
        "description": "The Ellinikon ΓÇô Marina Residences is part of The Ellinikon masterplan, a massive urban regeneration project led by LAMDA Development. It provides luxury living on the Athens Riviera coastline, closely situated to the Ellinikon Metropolitan Park, Riviera Galleria, and local marinas.",
        "specs": [
            {"label": "Location", "value": "Elliniko / Agios Kosmas Marina, Athens"},
            {"label": "Developer", "value": "LAMDA Development"},
            {"label": "Units Available", "value": "178 of 200"},
            {"label": "Completion", "value": "June 2026"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Not applicable"},
            {"label": "Rental Yield", "value": "5% estimated"},
            {"label": "Price Range", "value": "Γé¼1,000,000 ΓÇô Γé¼20,000,000"},
        ],
        "tags": ["Waterfront", "Master-planned community", "Under construction"],
        "score_reasons": [
            "Greece matches geographic preference",
            "Strong upside potential from large-scale urban regeneration",
            "Prime waterfront positioning on the Athens Riviera",
        ],
        # Sourced directly from Excel ΓÇö Lamda Development (Riviera Tower profile)
        "determinant_scores": {
            "project_exit_liquidity": 4.0,
            "expected_rental_yield": 5.0,
            "public_infrastructure_proximity": 5.0,
            "financial_strength": 10.0,
            "project_completion_rate": 9.0,
            "construction_quality": 10.0,
            "litigation_history": 7.0,
            "delivery_history": 5.0,
        },
    },

    # ΓöÇΓöÇΓöÇ THAILAND ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

    "laguna": {
        "project_name": "Laguna Lakelands",
        "country": "Thailand",
        "city": "Phuket",
        "flag": "≡ƒç╣≡ƒç¡",
        "image": "https://images.unsplash.com/photo-1540541338537-41943b0ace37?w=800",
        "developer": "Banyan Group",
        "price_range": "α╕┐6.8M ΓÇô α╕┐60M",
        "project_type": "Mixed-use Resort",
        "project_stage": "Under Construction",
        "ownership": "Freehold",
        "golden_visa": False,
        "rental_yield_display": "7% ΓÇô 10%",
        "highlight": "Banyan Group integrated resort residences with professional rental management",
        "description": "Laguna Lakelands is the flagship development within Laguna Phuket ΓÇö Asia's most successful integrated resort destination, developed and operated by Banyan Group over 30+ years. The mixed-use project combines villa and condo residences with a world-class golf course, beach club, spa, and hotel infrastructure.",
        "specs": [
            {"label": "Location", "value": "Bang Tao / Laguna Phuket, Phuket"},
            {"label": "Developer", "value": "Banyan Group"},
            {"label": "Units Available", "value": "210 of 6,000"},
            {"label": "Completion", "value": "March 2027"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Not applicable"},
            {"label": "Rental Yield", "value": "7% ΓÇô 10% estimated"},
            {"label": "Price Range", "value": "$6,800,000 ΓÇô $60,000,000"},
        ],
        "tags": ["Mixed-use yield play", "Banyan Group managed", "Under construction upside", "Airport & beach access"],
        "score_reasons": [
            "Thailand matches your geographic preference",
            "Mixed-use structure maximises yield for cash flow investors",
            "Under construction stage suits opportunistic risk appetite",
            "Banyan rental management removes operational burden",
        ],
        # Banyan Group: extensive track record, institutional operator
        "determinant_scores": {
            "project_exit_liquidity": 3.0,
            "expected_rental_yield": 8.5,
            "public_infrastructure_proximity": 3.0,
            "financial_strength": 9.0,
            "project_completion_rate": 9.0,
            "construction_quality": 9.0,
            "litigation_history": 8.0,
            "delivery_history": 5.0,
        },
    },

    "hythe": {
        "project_name": "HYTHE by Botanica",
        "country": "Thailand",
        "city": "Phuket",
        "flag": "≡ƒç╣≡ƒç¡",
        "image": "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800",
        "developer": "Botanica Luxury Phuket Co., Ltd.",
        "price_range": "α╕┐10.8M ΓÇô α╕┐165M",
        "project_type": "Residential Villas",
        "project_stage": "Under Construction",
        "ownership": "Freehold",
        "golden_visa": False,
        "rental_yield_display": "6% ΓÇô 9%",
        "highlight": "Ultra-luxury Phuket villas by Botanica with 20+ year development track record",
        "description": "HYTHE by Botanica is an ultra-luxury villa development in Cherngtalay, Phuket's most exclusive residential enclave within Laguna Phuket. Developed by Botanica Luxury ΓÇö with 20+ years and 15+ delivered projects in Phuket ΓÇö HYTHE targets high-net-worth investors seeking a trophy lifestyle asset.",
        "specs": [
            {"label": "Location", "value": "Cherngtalay / Laguna Phuket, Phuket"},
            {"label": "Developer", "value": "Botanica Luxury Phuket Co., Ltd."},
            {"label": "Units Available", "value": "21 of 276"},
            {"label": "Completion", "value": "December 2026"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Not applicable"},
            {"label": "Rental Yield", "value": "6% ΓÇô 9% estimated"},
            {"label": "Price Range", "value": "$10,800,000 ΓÇô $165,000,000"},
        ],
        "tags": ["Phuket luxury villas", "Under construction upside", "20+ year track record", "Beach club proximity"],
        "score_reasons": [
            "Thailand matches your geographic preference",
            "Under construction stage suits opportunistic risk appetite",
            "Botanica track record: 20+ years, 15+ delivered Phuket projects",
            "Beach and airport proximity drives premium rental occupancy",
        ],
        # Botanica: strong villa track record, private developer, no litigation
        "determinant_scores": {
            "project_exit_liquidity": 2.0,
            "expected_rental_yield": 7.5,
            "public_infrastructure_proximity": 3.0,
            "financial_strength": 5.0,
            "project_completion_rate": 8.0,
            "construction_quality": 8.0,
            "litigation_history": 7.0,
            "delivery_history": 4.0,
        },
    },

    "noble": {
        "project_name": "Noble Ploenchit",
        "country": "Thailand",
        "city": "Bangkok",
        "flag": "≡ƒç╣≡ƒç¡",
        "image": "https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800",
        "developer": "Noble Development Public Co., Ltd.",
        "price_range": "α╕┐8.5M ΓÇô α╕┐185M",
        "project_type": "Residential",
        "project_stage": "Ready to Move",
        "ownership": "Freehold",
        "golden_visa": False,
        "rental_yield_display": "5% ΓÇô 7%",
        "highlight": "Bangkok CBD premium residential with direct BTS access and strong resale liquidity",
        "description": "Noble Ploenchit occupies one of Bangkok's most coveted residential addresses ΓÇö Phloen Chit Road in Lumphini, Pathum Wan ΓÇö directly connected to BTS Phloen Chit Station. For yield investors, Bangkok CBD condos at this location command premium rental rates from international executives and diplomats year-round.",
        "specs": [
            {"label": "Location", "value": "Phloen Chit Road, Lumphini, Bangkok"},
            {"label": "Developer", "value": "Noble Development Public Co., Ltd."},
            {"label": "Units Available", "value": "1,223 of 1,444"},
            {"label": "Completion", "value": "December 2026"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Not applicable"},
            {"label": "Rental Yield", "value": "5% ΓÇô 7% estimated"},
            {"label": "Price Range", "value": "$8,500,000 ΓÇô $185,000,000"},
        ],
        "tags": ["BTS direct access", "Bangkok CBD", "Premium residential asset", "Strong resale liquidity"],
        "score_reasons": [
            "Thailand matches your geographic preference",
            "CBD location drives premium rental demand from expats and executives",
            "BTS direct access ΓÇö highest liquidity corridor in Bangkok",
            "Listed developer with strong delivery track record",
        ],
        # Noble Development: listed Thai developer, consistent track record
        "determinant_scores": {
            "project_exit_liquidity": 4.0,
            "expected_rental_yield": 6.0,
            "public_infrastructure_proximity": 5.0,
            "financial_strength": 8.0,
            "project_completion_rate": 9.0,
            "construction_quality": 8.0,
            "litigation_history": 7.0,
            "delivery_history": 5.0,
        },
    },

    "monument": {
        "project_name": "The Monument Thong Lo",
        "country": "Thailand",
        "city": "Bangkok",
        "flag": "≡ƒç╣≡ƒç¡",
        "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
        "developer": "Sansiri",
        "price_range": "α╕┐30M ΓÇô α╕┐150M",
        "project_type": "Residential",
        "project_stage": "Ready to Move",
        "ownership": "Freehold",
        "golden_visa": False,
        "rental_yield_display": "4% ΓÇô 6%",
        "highlight": "Sansiri ultra-luxury in Thong Lo ΓÇö Bangkok's most prestigious lifestyle address",
        "description": "The Monument Thong Lo is Sansiri's flagship ultra-luxury residential tower on Sukhumvit 55, Bangkok's most prestigious lifestyle corridor. Thong Lo commands the highest rental rates in Bangkok from Japanese expats, senior executives, and high-net-worth short-term tenants.",
        "specs": [
            {"label": "Location", "value": "Thong Lo (Sukhumvit 55), Watthana, Bangkok"},
            {"label": "Developer", "value": "Sansiri"},
            {"label": "Units Available", "value": "10 of 127"},
            {"label": "Completion", "value": "June 2026"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Not applicable"},
            {"label": "Rental Yield", "value": "4% ΓÇô 6% estimated"},
            {"label": "Price Range", "value": "$30,000,000 ΓÇô $150,000,000"},
        ],
        "tags": ["Thong Lo prestige", "Ultra-luxury", "Sansiri flagship", "Only 10 units remaining"],
        "score_reasons": [
            "Thailand matches your geographic preference",
            "Thong Lo commands Bangkok's highest per-sqm rental rates",
            "Sansiri brand reduces execution risk",
            "Only 10 units remaining ΓÇö genuine scarcity",
        ],
        # Sansiri: Thailand's largest listed developer, extensive track record
        "determinant_scores": {
            "project_exit_liquidity": 4.0,
            "expected_rental_yield": 5.0,
            "public_infrastructure_proximity": 5.0,
            "financial_strength": 9.0,
            "project_completion_rate": 9.2,
            "construction_quality": 9.0,
            "litigation_history": 8.0,
            "delivery_history": 5.0,
        },
    },

    # ΓöÇΓöÇΓöÇ UAE ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

    "greencrest": {
        "project_name": "Greencrest at Dubai Hills Estate",
        "country": "UAE",
        "city": "Dubai",
        "flag": "≡ƒçª≡ƒç¬",
        "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
        "developer": "Emaar Properties",
        "price_range": "AED 1.57M ΓÇô AED 3.89M",
        "project_type": "Residential",
        "project_stage": "Under Construction",
        "ownership": "Freehold",
        "golden_visa": True,
        "rental_yield_display": "6.5%",
        "highlight": "Emaar luxury residences in Dubai Hills with 6.5% yield and UAE Golden Visa",
        "description": "Greencrest at Dubai Hills Estate is an Emaar Properties development within the master-planned Dubai Hills community. The project sits adjacent to King's College Hospital London Dubai, GEMS International School, and Dubai Hills Mall.",
        "specs": [
            {"label": "Location", "value": "Dubai Hills Estate, MBR City"},
            {"label": "Developer", "value": "Emaar Properties"},
            {"label": "Units Available", "value": "20 of 195"},
            {"label": "Completion", "value": "June 2029"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Yes ΓÇö UAE Golden Visa eligible"},
            {"label": "Rental Yield", "value": "6.5% estimated"},
            {"label": "Price Range", "value": "$1,570,000 ΓÇô $3,890,000"},
        ],
        "tags": ["6.5% rental yield", "UAE Golden Visa", "King's College Hospital nearby", "Emaar brand", "0% capital gains tax"],
        "score_reasons": [
            "Conservative UAE stability bonus for portfolio diversification",
            "Golden Visa eligible ΓÇö UAE residency pathway",
            "King's College Hospital and GEMS school on doorstep",
            "Emaar track record reduces developer risk",
        ],
        # Sourced from Excel ΓÇö Emaar (Avarra by Palace profile)
        "determinant_scores": {
            "project_exit_liquidity": 4.0,
            "expected_rental_yield": 6.5,
            "public_infrastructure_proximity": 5.0,
            "financial_strength": 10.0,
            "project_completion_rate": 9.0,
            "construction_quality": 7.0,
            "litigation_history": 5.0,
            "delivery_history": 5.0,
        },
    },

    "sobha_hartland": {
        "project_name": "Sobha Hartland",
        "country": "UAE",
        "city": "Dubai",
        "flag": "≡ƒçª≡ƒç¬",
        "image": "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
        "developer": "Sobha Realty",
        "price_range": "AED 1.2M ΓÇô AED 85M",
        "project_type": "Mixed-use",
        "project_stage": "Under Construction",
        "ownership": "Freehold",
        "golden_visa": True,
        "rental_yield_display": "6.5%",
        "highlight": "Central luxury mixed-use community in Mohammed Bin Rashid City",
        "description": "Sobha Hartland is a master-planned development by Sobha Realty in Mohammed Bin Rashid City (MBR City), Dubai. It offers freehold ownership for foreign investors and is centrally located near Downtown Dubai, Burj Khalifa, and Hartland International School.",
        "specs": [
            {"label": "Location", "value": "Mohammed Bin Rashid City (MBR City), Dubai"},
            {"label": "Developer", "value": "Sobha Realty"},
            {"label": "Units Available", "value": "9 of 200"},
            {"label": "Completion", "value": "June 2027"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Yes ΓÇö UAE Golden Visa eligible"},
            {"label": "Rental Yield", "value": "6.5% estimated"},
            {"label": "Price Range", "value": "$1,200,000 ΓÇô $85,000,000"},
        ],
        "tags": ["Central location", "UAE Golden Visa", "Schools nearby"],
        "score_reasons": [
            "UAE stability bonus for portfolio diversification",
            "Golden Visa eligible for UAE residency",
            "Top-tier international schools within the community",
        ],
        # Sourced directly from Excel ΓÇö Sobha Hartland II profile
        "determinant_scores": {
            "project_exit_liquidity": 5.0,
            "expected_rental_yield": 7.0,
            "public_infrastructure_proximity": 2.0,
            "financial_strength": 9.0,
            "project_completion_rate": 9.0,
            "construction_quality": 10.0,
            "litigation_history": 6.0,
            "delivery_history": 5.0,
        },
    },

    "burj_binghatti": {
        "project_name": "Burj Binghatti Jacob & Co Residences",
        "country": "UAE",
        "city": "Dubai",
        "flag": "≡ƒçª≡ƒç¬",
        "image": "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800",
        "developer": "Binghatti Developers",
        "price_range": "AED 8.2M ΓÇô AED 752M",
        "project_type": "Residential",
        "project_stage": "Under Construction",
        "ownership": "Freehold",
        "golden_visa": True,
        "rental_yield_display": "4.5%",
        "highlight": "Ultra-luxury branded residences in Business Bay",
        "description": "Burj Binghatti Jacob & Co Residences is an ultra-luxury residential tower developed by Binghatti Developers in collaboration with the Jacob & Co brand. Located in Business Bay, it provides central access to Burj Khalifa, Dubai Mall, and the Dubai Opera.",
        "specs": [
            {"label": "Location", "value": "Business Bay, Dubai"},
            {"label": "Developer", "value": "Binghatti Developers"},
            {"label": "Units Available", "value": "40 of 299"},
            {"label": "Completion", "value": "June 2026"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Yes ΓÇö UAE Golden Visa eligible"},
            {"label": "Rental Yield", "value": "4.5% estimated"},
            {"label": "Price Range", "value": "$8,200,000 ΓÇô $752,000,000"},
        ],
        "tags": ["Branded residences", "Ultra-luxury", "UAE Golden Visa"],
        "score_reasons": [
            "Trophy asset status for high-net-worth portfolios",
            "Golden Visa eligible for UAE residency",
            "Close proximity to primary business district",
        ],
        # Sourced directly from Excel ΓÇö Binghatti Bugatti Residences profile
        "determinant_scores": {
            "project_exit_liquidity": 3.0,
            "expected_rental_yield": 4.5,
            "public_infrastructure_proximity": 4.0,
            "financial_strength": 4.0,
            "project_completion_rate": 7.5,
            "construction_quality": 4.0,
            "litigation_history": 8.0,
            "delivery_history": 4.0,
        },
    },

    "damac_islands": {
        "project_name": "DAMAC Islands",
        "country": "UAE",
        "city": "Dubai",
        "flag": "≡ƒçª≡ƒç¬",
        "image": "https://images.unsplash.com/photo-1526495124232-a04e1849168c?w=800",
        "developer": "DAMAC Properties",
        "price_range": "AED 2.25M ΓÇô AED 9.5M",
        "project_type": "Mixed-use",
        "project_stage": "Under Construction",
        "ownership": "Freehold",
        "golden_visa": True,
        "rental_yield_display": "6%",
        "highlight": "Emerging mixed-use community with waterfront lagoons in Dubailand",
        "description": "DAMAC Islands is an emerging mixed-use master community located in Dubailand. Developed by DAMAC Properties, the development centers around waterfront lagoons and resort amenities with strong connectivity to Emirates Road.",
        "specs": [
            {"label": "Location", "value": "Dubailand, Dubai"},
            {"label": "Developer", "value": "DAMAC Properties"},
            {"label": "Units Available", "value": "45 of 200"},
            {"label": "Completion", "value": "December 2028"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Yes ΓÇö UAE Golden Visa eligible"},
            {"label": "Rental Yield", "value": "6% estimated"},
            {"label": "Price Range", "value": "$2,250,000 ΓÇô $9,500,000"},
        ],
        "tags": ["Waterfront community", "Resort lifestyle", "UAE Golden Visa"],
        "score_reasons": [
            "Emerging location offers capital appreciation potential",
            "Golden Visa eligible for UAE residency",
            "Established mega-developer execution",
        ],
        # Sourced directly from Excel ΓÇö Damac Elegance Tower profile
        "determinant_scores": {
            "project_exit_liquidity": 4.0,
            "expected_rental_yield": 6.0,
            "public_infrastructure_proximity": 5.0,
            "financial_strength": 8.0,
            "project_completion_rate": 8.0,
            "construction_quality": 5.0,
            "litigation_history": 5.0,
            "delivery_history": 5.0,
        },
    },

    "dubai_creek": {
        "project_name": "Dubai Creek Harbour",
        "country": "UAE",
        "city": "Dubai",
        "flag": "≡ƒçª≡ƒç¬",
        "image": "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800",
        "developer": "Emaar Properties",
        "price_range": "AED 1.2M ΓÇô AED 15M",
        "project_type": "Mixed-use",
        "project_stage": "Under Construction",
        "ownership": "Freehold",
        "golden_visa": True,
        "rental_yield_display": "6.5%",
        "highlight": "Emaar's massive waterfront masterplan offering strong rental yields",
        "description": "Dubai Creek Harbour is a major master-planned community by Emaar Properties in the Ras Al Khor area. This emerging mixed-use development offers residents access to Creek Marina, Creek Beach, and the Ras Al Khor Wildlife Sanctuary.",
        "specs": [
            {"label": "Location", "value": "Dubai Creek Harbour (The Lagoons), Dubai"},
            {"label": "Developer", "value": "Emaar Properties"},
            {"label": "Units Available", "value": "12,000 of 48,500"},
            {"label": "Completion", "value": "December 2028"},
            {"label": "Ownership", "value": "Freehold"},
            {"label": "Golden Visa", "value": "Yes ΓÇö UAE Golden Visa eligible"},
            {"label": "Rental Yield", "value": "6.5% estimated"},
            {"label": "Price Range", "value": "$1,200,000 ΓÇô $15,000,000"},
        ],
        "tags": ["Emaar brand", "Waterfront", "6.5% rental yield", "UAE Golden Visa"],
        "score_reasons": [
            "Emaar track record significantly reduces execution risk",
            "Golden Visa eligible for UAE residency",
            "0% capital gains tax and tax-free rental income in UAE",
        ],
        # Emaar: same profile as Greencrest, slightly lower infra proximity
        "determinant_scores": {
            "project_exit_liquidity": 4.0,
            "expected_rental_yield": 6.5,
            "public_infrastructure_proximity": 4.0,
            "financial_strength": 10.0,
            "project_completion_rate": 9.0,
            "construction_quality": 7.0,
            "litigation_history": 5.0,
            "delivery_history": 5.0,
        },
    },
}


# ΓöÇΓöÇΓöÇ HELPER FUNCTIONS ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

def get_projects_by_country(country: str) -> dict:
    """Return all projects for a given country name."""
    return {k: v for k, v in PROJECTS.items() if v["country"] == country}


def get_projects_by_cities(city_list: list) -> dict:
    """Return all projects whose city is in the provided list."""
    city_set = set(city_list)
    return {k: v for k, v in PROJECTS.items() if v["city"] in city_set}


def get_projects_by_countries(country_list: list) -> dict:
    """Return all projects whose country is in the provided list."""
    country_set = set(country_list)
    return {k: v for k, v in PROJECTS.items() if v["country"] in country_set}


def list_determinant_keys() -> list:
    """Return the 8 determinant keys used for scoring."""
    return [
        "project_exit_liquidity",
        "expected_rental_yield",
        "public_infrastructure_proximity",
        "financial_strength",
        "project_completion_rate",
        "construction_quality",
        "litigation_history",
        "delivery_history",
    ]
