"""
projects_data.py — Consolidated project asset data for all four countries.
Sources: project_scores.xlsx (Database for Engine tab) — June 2026 update.
All raw_variables are 0-100 magnitude scores. Engine handles inversion.
"""

PROJECTS = {

    "ellinikon_marina_residences": {
        "project_name": 'The Ellinikon – Marina Residences',
        "country": 'Greece',
        "city": 'Athens',
        "price_range": '€1M – €20M',
        "project_stage": 'Under Construction',
        "ownership": 'freehold',
        "project_type": 'apartment',
        "highlight": "Luxury waterfront living within Europe's largest urban regeneration project",
        "description": 'The Ellinikon – Marina Residences is part of The Ellinikon masterplan, a massive urban regeneration project led by LAMDA Development. It provides luxury living on the Athens Riviera coastline, closely situated to the Ellinikon Metropolitan Park, Riviera Galleria, and local marinas.',
        "tags": ['Waterfront', 'Master-planned community', 'Under construction'],

        "raw_variables": {
            "micro_market_stage": 75.0,
            "rental_absorption_velocity": 26.67,
            "days_on_market": 50.0,
            "occupancy_vacancy_rate": 83.33,
            "resale_velocity": 33.33,
            "safety_crime_index": 41.5,
            "air_quality_index": 17.33,
            "healthcare_access": 75.0,
            "school_quality": 88.0,
            "beach_coastal_access": 100.0,
            "population_growth_rate": 25.0,
            "expat_concentration": 16.67,
            "active_unsold_inventory": 37.5,
            "immediate_pipeline_risk": 33.33,
            "pct_projects_delivered": 90.0,
            "average_delay_duration": 8.33,
            "completion_consistency": 16.67,
            "debt_cash_position": 40.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 81.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 18.18,
            "flipping_frequency": 50.0,
            "projected_rental_yield": 25.0,
            "infrastructure_proximity": 100.0,
            "comp_capital_appreciation": 66.0,
            "comp_rental_yields": 25.0,
            "comp_occupancy_rate": 80.0,
            "investor_owner_ratio": 60.0,
            "offplan_secondary_dominance": 81.0,
            "str_concentration": 100.0,
        },
    },

    "one_athens": {
        "project_name": 'One Athens',
        "country": 'Greece',
        "city": 'Athens',
        "price_range": '€200K – €4.5M',
        "project_stage": 'Ready',
        "ownership": 'freehold',
        "project_type": 'apartment',
        "highlight": 'Ready-to-move residential redevelopment in central Athens',
        "description": 'One Athens is a residential redevelopment project delivered by DIMAND. Located in Kolonaki / Athens City Centre, it offers central proximity to the Athens Concert Hall, embassies, luxury retail, and museums.',
        "tags": ['Ready to move in', 'City centre', 'Luxury retail access'],

        "raw_variables": {
            "micro_market_stage": 100.0,
            "rental_absorption_velocity": 16.67,
            "days_on_market": 66.67,
            "occupancy_vacancy_rate": 96.67,
            "resale_velocity": 50.0,
            "safety_crime_index": 44.8,
            "air_quality_index": 16.0,
            "healthcare_access": 100.0,
            "school_quality": 92.0,
            "beach_coastal_access": 50.0,
            "population_growth_rate": 19.0,
            "expat_concentration": 11.11,
            "active_unsold_inventory": 12.5,
            "immediate_pipeline_risk": 16.67,
            "pct_projects_delivered": 95.0,
            "average_delay_duration": 4.17,
            "completion_consistency": 8.33,
            "debt_cash_position": 60.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 100.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 27.27,
            "flipping_frequency": 16.67,
            "projected_rental_yield": 20.0,
            "infrastructure_proximity": 100.0,
            "comp_capital_appreciation": 44.8,
            "comp_rental_yields": 20.0,
            "comp_occupancy_rate": 88.0,
            "investor_owner_ratio": 40.0,
            "offplan_secondary_dominance": 0.0,
            "str_concentration": 80.0,
        },
    },

    "luxeasy_thessaloniki": {
        "project_name": 'LUX&EASY Thessaloniki',
        "country": 'Greece',
        "city": 'Thessaloniki',
        "price_range": '€120K – €240K',
        "project_stage": 'Under Construction',
        "ownership": 'freehold',
        "project_type": 'apartment',
        "highlight": 'High-volume branded residences with strong Greek Golden Visa pathway',
        "description": "LUX&EASY Thessaloniki is a large-scale branded residential development by NOVA CONSTRUCTIONS S.A. in Greece's second-largest city. With over 2,300 units across the Thessaloniki Metropolitan Area, the project offers the lowest entry point into the Greek Golden Visa program at €120,000 — well below Athens pricing.",
        "tags": ['Golden Visa eligible', 'Lowest entry point', 'Central urban location', 'Family infrastructure nearby'],

        "raw_variables": {
            "micro_market_stage": 75.0,
            "rental_absorption_velocity": 13.33,
            "days_on_market": 41.67,
            "occupancy_vacancy_rate": 100.0,
            "resale_velocity": 30.56,
            "safety_crime_index": 46.2,
            "air_quality_index": 18.33,
            "healthcare_access": 100.0,
            "school_quality": 85.0,
            "beach_coastal_access": 75.0,
            "population_growth_rate": 24.0,
            "expat_concentration": 11.11,
            "active_unsold_inventory": 25.0,
            "immediate_pipeline_risk": 50.0,
            "pct_projects_delivered": 85.0,
            "average_delay_duration": 12.5,
            "completion_consistency": 25.0,
            "debt_cash_position": 65.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 75.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 22.73,
            "flipping_frequency": 66.67,
            "projected_rental_yield": 40.0,
            "infrastructure_proximity": 100.0,
            "comp_capital_appreciation": 58.4,
            "comp_rental_yields": 40.0,
            "comp_occupancy_rate": 84.0,
            "investor_owner_ratio": 50.0,
            "offplan_secondary_dominance": 75.0,
            "str_concentration": 100.0,
        },
    },

    "palmares": {
        "project_name": 'Palmares Ocean Living & Golf Resort',
        "country": 'Portugal',
        "city": 'Algarve',
        "price_range": '€199K – €1.1M',
        "project_stage": 'Under Construction',
        "ownership": 'freehold',
        "project_type": 'managed',
        "highlight": 'Golf resort residences on the Algarve coast with Golden Visa access',
        "description": "Palmares Ocean Living & Golf Resort occupies a spectacular position on the Algarve coast near Lagos, set within a world-class golf resort overlooking Meia Praia beach and the Alvor estuary. Developed by Oxy Capital, the project offers branded resort residences with full property management, rental pooling, and Golden Visa eligibility. Algarve's status as Europe's premier golf and lifestyle destination makes this a high-conviction hold for families seeking residency with strong leisure upside.",
        "tags": ['Golden Visa eligible', 'Resort lifestyle', 'Under construction upside', 'Algarve coastal'],

        "raw_variables": {
            "micro_market_stage": 100.0,
            "rental_absorption_velocity": 10.0,
            "days_on_market": 33.33,
            "occupancy_vacancy_rate": 33.33,
            "resale_velocity": 41.67,
            "safety_crime_index": 81.5,
            "air_quality_index": 15.0,
            "healthcare_access": 75.0,
            "school_quality": 85.0,
            "beach_coastal_access": 100.0,
            "population_growth_rate": 28.0,
            "expat_concentration": 38.89,
            "active_unsold_inventory": 37.5,
            "immediate_pipeline_risk": 33.33,
            "pct_projects_delivered": 95.0,
            "average_delay_duration": 4.17,
            "completion_consistency": 12.5,
            "debt_cash_position": 20.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 70.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 27.27,
            "flipping_frequency": 33.33,
            "projected_rental_yield": 35.0,
            "infrastructure_proximity": 50.0,
            "comp_capital_appreciation": 68.0,
            "comp_rental_yields": 35.0,
            "comp_occupancy_rate": 80.0,
            "investor_owner_ratio": 60.0,
            "offplan_secondary_dominance": 50.0,
            "str_concentration": 100.0,
        },
    },

    "amoreiras_prime": {
        "project_name": 'Amoreiras Prime Residences',
        "country": 'Portugal',
        "city": 'Lisbon',
        "price_range": '€750K – €3.5M',
        "project_stage": 'Ready',
        "ownership": 'freehold',
        "project_type": 'apartment',
        "highlight": "Landmark luxury development in Lisbon's most connected neighbourhood",
        "description": "Amoreiras Prime Residences is a landmark luxury development by Vanguard Properties in the heart of Lisbon's Amoreiras district — home to the Amoreiras Shopping Centre, the Lycée Français Charles Lepierre, and direct access to the Marquês de Pombal business corridor. With only 34 units across a boutique building, the project offers genuine scarcity value, Golden Visa eligibility, and the Vanguard brand guarantee.",
        "tags": ['Golden Visa eligible', 'French school nearby', 'Business district access', 'Vanguard luxury brand'],

        "raw_variables": {
            "micro_market_stage": 100.0,
            "rental_absorption_velocity": 20.0,
            "days_on_market": 25.0,
            "occupancy_vacancy_rate": 16.67,
            "resale_velocity": 22.22,
            "safety_crime_index": 67.4,
            "air_quality_index": 18.33,
            "healthcare_access": 100.0,
            "school_quality": 90.0,
            "beach_coastal_access": 50.0,
            "population_growth_rate": 24.7,
            "expat_concentration": 22.22,
            "active_unsold_inventory": 12.5,
            "immediate_pipeline_risk": 16.67,
            "pct_projects_delivered": 90.0,
            "average_delay_duration": 8.33,
            "completion_consistency": 16.67,
            "debt_cash_position": 30.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 90.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 18.18,
            "flipping_frequency": 50.0,
            "projected_rental_yield": 25.0,
            "infrastructure_proximity": 100.0,
            "comp_capital_appreciation": 62.0,
            "comp_rental_yields": 25.0,
            "comp_occupancy_rate": 90.0,
            "investor_owner_ratio": 40.0,
            "offplan_secondary_dominance": 20.0,
            "str_concentration": 60.0,
        },
    },

    "infante_residences": {
        "project_name": 'Infante Residences',
        "country": 'Portugal',
        "city": 'Lisbon',
        "price_range": '€399K – €1.01M',
        "project_stage": 'Under Construction',
        "ownership": 'freehold',
        "project_type": 'apartment',
        "highlight": "Rehabilitation condominium development in Lisbon's central district",
        "description": 'Infante Residences is a rehabilitation condominium development located in the Estrela / Avenida Infante Santo area of Lisbon. Developed by Vanguard Properties, the project is situated near Jardim da Estrela, LX Factory, Amoreiras, and Hospital CUF Tejo.',
        "tags": ['Central location', 'Rehabilitation project', 'Hospitals nearby'],

        "raw_variables": {
            "micro_market_stage": 75.0,
            "rental_absorption_velocity": 13.33,
            "days_on_market": 27.78,
            "occupancy_vacancy_rate": 26.67,
            "resale_velocity": 30.56,
            "safety_crime_index": 67.4,
            "air_quality_index": 18.33,
            "healthcare_access": 100.0,
            "school_quality": 88.0,
            "beach_coastal_access": 50.0,
            "population_growth_rate": 24.7,
            "expat_concentration": 27.78,
            "active_unsold_inventory": 25.0,
            "immediate_pipeline_risk": 50.0,
            "pct_projects_delivered": 85.0,
            "average_delay_duration": 12.5,
            "completion_consistency": 25.0,
            "debt_cash_position": 40.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 80.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 22.73,
            "flipping_frequency": 66.67,
            "projected_rental_yield": 30.0,
            "infrastructure_proximity": 100.0,
            "comp_capital_appreciation": 64.8,
            "comp_rental_yields": 30.0,
            "comp_occupancy_rate": 84.0,
            "investor_owner_ratio": 70.0,
            "offplan_secondary_dominance": 85.0,
            "str_concentration": 100.0,
        },
    },

    "the_lisboans": {
        "project_name": 'The Lisboans',
        "country": 'Portugal',
        "city": 'Lisbon',
        "price_range": '€450K – €2.5M',
        "project_stage": 'Ready',
        "ownership": 'freehold',
        "project_type": 'managed',
        "highlight": "Premium hospitality-lifestyle residences in Lisbon's historic core",
        "description": "The Lisboans is a landmark hospitality-residential concept in Alfama, Lisbon's oldest and most iconic district. Developed by Oxy Capital, the project blends boutique hotel services with private residential ownership, offering investors a rare combination of lifestyle asset and Golden Visa eligibility. Located steps from Praça do Comércio and the Tagus riverfront, residents enjoy 5-star amenities, concierge services, and direct access to Lisbon's most sought-after cultural and dining destinations.",
        "tags": ['Golden Visa eligible', 'Within budget', 'Schools & hospitals nearby', 'Ready to move in'],

        "raw_variables": {
            "micro_market_stage": 100.0,
            "rental_absorption_velocity": 6.67,
            "days_on_market": 19.44,
            "occupancy_vacancy_rate": 40.0,
            "resale_velocity": 25.0,
            "safety_crime_index": 67.4,
            "air_quality_index": 18.33,
            "healthcare_access": 100.0,
            "school_quality": 85.0,
            "beach_coastal_access": 50.0,
            "population_growth_rate": 24.7,
            "expat_concentration": 33.33,
            "active_unsold_inventory": 5.0,
            "immediate_pipeline_risk": 6.67,
            "pct_projects_delivered": 100.0,
            "average_delay_duration": 0.0,
            "completion_consistency": 0.0,
            "debt_cash_position": 10.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 100.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 13.64,
            "flipping_frequency": 16.67,
            "projected_rental_yield": 40.0,
            "infrastructure_proximity": 100.0,
            "comp_capital_appreciation": 74.0,
            "comp_rental_yields": 40.0,
            "comp_occupancy_rate": 76.0,
            "investor_owner_ratio": 30.0,
            "offplan_secondary_dominance": 0.0,
            "str_concentration": 100.0,
        },
    },

    "monument_thong_lo": {
        "project_name": 'The Monument Thong Lo',
        "country": 'Thailand',
        "city": 'Bangkok',
        "price_range": '฿30M – ฿150M',
        "project_stage": 'Ready',
        "ownership": 'freehold',
        "project_type": 'apartment',
        "highlight": "Sansiri ultra-luxury in Thong Lo — Bangkok's most prestigious lifestyle address",
        "description": "The Monument Thong Lo is Sansiri's flagship ultra-luxury residential tower on Sukhumvit 55, Bangkok's most prestigious lifestyle corridor. Thong Lo commands the highest rental rates in Bangkok from Japanese expats, senior executives, and high-net-worth short-term tenants.",
        "tags": ['Thong Lo prestige', 'Ultra-luxury', 'Sansiri flagship', 'Only 10 units remaining'],

        "raw_variables": {
            "micro_market_stage": 100.0,
            "rental_absorption_velocity": 26.67,
            "days_on_market": 30.56,
            "occupancy_vacancy_rate": 40.0,
            "resale_velocity": 38.89,
            "safety_crime_index": 58.8,
            "air_quality_index": 46.67,
            "healthcare_access": 75.0,
            "school_quality": 90.0,
            "beach_coastal_access": 0.0,
            "population_growth_rate": 31.0,
            "expat_concentration": 61.11,
            "active_unsold_inventory": 25.0,
            "immediate_pipeline_risk": 50.0,
            "pct_projects_delivered": 95.0,
            "average_delay_duration": 6.25,
            "completion_consistency": 12.5,
            "debt_cash_position": 55.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 100.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 27.27,
            "flipping_frequency": 26.67,
            "projected_rental_yield": 20.0,
            "infrastructure_proximity": 100.0,
            "comp_capital_appreciation": 42.0,
            "comp_rental_yields": 20.0,
            "comp_occupancy_rate": 76.0,
            "investor_owner_ratio": 50.0,
            "offplan_secondary_dominance": 5.0,
            "str_concentration": 32.0,
        },
    },

    "noble_ploenchit": {
        "project_name": 'Noble Ploenchit',
        "country": 'Thailand',
        "city": 'Bangkok',
        "price_range": '฿8.5M – ฿185M',
        "project_stage": 'Ready',
        "ownership": 'freehold',
        "project_type": 'apartment',
        "highlight": 'Bangkok CBD premium residential with direct BTS access and strong resale liquidity',
        "description": "Noble Ploenchit occupies one of Bangkok's most coveted residential addresses — Phloen Chit Road in Lumphini, Pathum Wan — directly connected to BTS Phloen Chit Station. For yield investors, Bangkok CBD condos at this location command premium rental rates from international executives and diplomats year-round.",
        "tags": ['BTS direct access', 'Bangkok CBD', 'Premium residential asset', 'Strong resale liquidity'],

        "raw_variables": {
            "micro_market_stage": 100.0,
            "rental_absorption_velocity": 43.33,
            "days_on_market": 25.0,
            "occupancy_vacancy_rate": 33.33,
            "resale_velocity": 33.33,
            "safety_crime_index": 58.8,
            "air_quality_index": 46.67,
            "healthcare_access": 75.0,
            "school_quality": 85.0,
            "beach_coastal_access": 0.0,
            "population_growth_rate": 31.0,
            "expat_concentration": 50.0,
            "active_unsold_inventory": 37.5,
            "immediate_pipeline_risk": 40.0,
            "pct_projects_delivered": 92.0,
            "average_delay_duration": 8.33,
            "completion_consistency": 16.67,
            "debt_cash_position": 60.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 95.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 22.73,
            "flipping_frequency": 40.0,
            "projected_rental_yield": 25.0,
            "infrastructure_proximity": 100.0,
            "comp_capital_appreciation": 36.8,
            "comp_rental_yields": 25.0,
            "comp_occupancy_rate": 80.0,
            "investor_owner_ratio": 60.0,
            "offplan_secondary_dominance": 15.0,
            "str_concentration": 60.0,
        },
    },

    "hythe_by_botanica": {
        "project_name": 'HYTHE by Botanica',
        "country": 'Thailand',
        "city": 'Phuket',
        "price_range": '฿10.8M – ฿165M',
        "project_stage": 'Under Construction',
        "ownership": 'freehold',
        "project_type": 'villa',
        "highlight": 'Ultra-luxury Phuket villas by Botanica with 20+ year development track record',
        "description": "HYTHE by Botanica is an ultra-luxury villa development in Cherngtalay, Phuket's most exclusive residential enclave within Laguna Phuket. Developed by Botanica Luxury — with 20+ years and 15+ delivered projects in Phuket — HYTHE targets high-net-worth investors seeking a trophy lifestyle asset.",
        "tags": ['Phuket luxury villas', 'Under construction upside', '20+ year track record', 'Beach club proximity'],

        "raw_variables": {
            "micro_market_stage": 100.0,
            "rental_absorption_velocity": 13.33,
            "days_on_market": 19.44,
            "occupancy_vacancy_rate": 50.0,
            "resale_velocity": 25.0,
            "safety_crime_index": 67.5,
            "air_quality_index": 30.0,
            "healthcare_access": 50.0,
            "school_quality": 75.0,
            "beach_coastal_access": 50.0,
            "population_growth_rate": 45.0,
            "expat_concentration": 72.22,
            "active_unsold_inventory": 62.5,
            "immediate_pipeline_risk": 93.33,
            "pct_projects_delivered": 94.0,
            "average_delay_duration": 4.17,
            "completion_consistency": 8.33,
            "debt_cash_position": 30.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 80.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 13.64,
            "flipping_frequency": 60.0,
            "projected_rental_yield": 40.0,
            "infrastructure_proximity": 50.0,
            "comp_capital_appreciation": 54.0,
            "comp_rental_yields": 40.0,
            "comp_occupancy_rate": 70.0,
            "investor_owner_ratio": 80.0,
            "offplan_secondary_dominance": 85.0,
            "str_concentration": 80.0,
        },
    },

    "laguna_lakelands": {
        "project_name": 'Laguna Lakelands',
        "country": 'Thailand',
        "city": 'Phuket',
        "price_range": '฿6.8M – ฿60M',
        "project_stage": 'Under Construction',
        "ownership": 'freehold',
        "project_type": 'managed',
        "highlight": 'Banyan Group integrated resort residences with professional rental management',
        "description": "Laguna Lakelands is the flagship development within Laguna Phuket — Asia's most successful integrated resort destination, developed and operated by Banyan Group over 30+ years. The mixed-use project combines villa and condo residences with a world-class golf course, beach club, spa, and hotel infrastructure.",
        "tags": ['Mixed-use yield play', 'Banyan Group managed', 'Under construction upside', 'Airport & beach access'],

        "raw_variables": {
            "micro_market_stage": 100.0,
            "rental_absorption_velocity": 20.0,
            "days_on_market": 22.22,
            "occupancy_vacancy_rate": 46.67,
            "resale_velocity": 27.78,
            "safety_crime_index": 67.5,
            "air_quality_index": 30.0,
            "healthcare_access": 50.0,
            "school_quality": 75.0,
            "beach_coastal_access": 75.0,
            "population_growth_rate": 45.0,
            "expat_concentration": 66.67,
            "active_unsold_inventory": 50.0,
            "immediate_pipeline_risk": 73.33,
            "pct_projects_delivered": 96.0,
            "average_delay_duration": 4.17,
            "completion_consistency": 8.33,
            "debt_cash_position": 15.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 75.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 18.18,
            "flipping_frequency": 50.0,
            "projected_rental_yield": 35.0,
            "infrastructure_proximity": 100.0,
            "comp_capital_appreciation": 48.0,
            "comp_rental_yields": 35.0,
            "comp_occupancy_rate": 72.0,
            "investor_owner_ratio": 75.0,
            "offplan_secondary_dominance": 90.0,
            "str_concentration": 48.0,
        },
    },

    "burj_binghatti": {
        "project_name": 'Burj Binghatti Jacob & Co Residences',
        "country": 'UAE',
        "city": 'Dubai',
        "price_range": 'AED 8.2M – AED 752M',
        "project_stage": 'Under Construction',
        "ownership": 'freehold',
        "project_type": 'branded',
        "highlight": 'Ultra-luxury branded residences in Business Bay',
        "description": 'Burj Binghatti Jacob & Co Residences is an ultra-luxury residential tower developed by Binghatti Developers in collaboration with the Jacob & Co brand. Located in Business Bay, it provides central access to Burj Khalifa, Dubai Mall, and the Dubai Opera.',
        "tags": ['Branded residences', 'Ultra-luxury', 'UAE Golden Visa'],

        "raw_variables": {
            "micro_market_stage": 100.0,
            "rental_absorption_velocity": 83.33,
            "days_on_market": 16.67,
            "occupancy_vacancy_rate": 26.67,
            "resale_velocity": 19.44,
            "safety_crime_index": 83.9,
            "air_quality_index": 34.33,
            "healthcare_access": 100.0,
            "school_quality": 80.0,
            "beach_coastal_access": 50.0,
            "population_growth_rate": 34.4,
            "expat_concentration": 100.0,
            "active_unsold_inventory": 50.0,
            "immediate_pipeline_risk": 83.33,
            "pct_projects_delivered": 85.0,
            "average_delay_duration": 12.5,
            "completion_consistency": 25.0,
            "debt_cash_position": 40.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 85.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 9.09,
            "flipping_frequency": 83.33,
            "projected_rental_yield": 42.0,
            "infrastructure_proximity": 100.0,
            "comp_capital_appreciation": 66.0,
            "comp_rental_yields": 42.0,
            "comp_occupancy_rate": 84.0,
            "investor_owner_ratio": 85.0,
            "offplan_secondary_dominance": 80.0,
            "str_concentration": 88.0,
        },
    },

    "damac_islands": {
        "project_name": 'DAMAC Islands',
        "country": 'UAE',
        "city": 'Dubai',
        "price_range": 'AED 2.25M – AED 9.5M',
        "project_stage": 'Under Construction',
        "ownership": 'freehold',
        "project_type": 'managed',
        "highlight": 'Emerging mixed-use community with waterfront lagoons in Dubailand',
        "description": 'DAMAC Islands is an emerging mixed-use master community located in Dubailand. Developed by DAMAC Properties, the development centers around waterfront lagoons and resort amenities with strong connectivity to Emirates Road.',
        "tags": ['Waterfront community', 'Resort lifestyle', 'UAE Golden Visa'],

        "raw_variables": {
            "micro_market_stage": 50.0,
            "rental_absorption_velocity": 16.67,
            "days_on_market": 22.22,
            "occupancy_vacancy_rate": 33.33,
            "resale_velocity": 27.78,
            "safety_crime_index": 83.9,
            "air_quality_index": 34.33,
            "healthcare_access": 50.0,
            "school_quality": 70.0,
            "beach_coastal_access": 50.0,
            "population_growth_rate": 34.4,
            "expat_concentration": 100.0,
            "active_unsold_inventory": 87.5,
            "immediate_pipeline_risk": 100.0,
            "pct_projects_delivered": 88.0,
            "average_delay_duration": 16.67,
            "completion_consistency": 33.33,
            "debt_cash_position": 25.0,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 90.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 22.73,
            "flipping_frequency": 100.0,
            "projected_rental_yield": 55.0,
            "infrastructure_proximity": 50.0,
            "comp_capital_appreciation": 80.0,
            "comp_rental_yields": 55.0,
            "comp_occupancy_rate": 80.0,
            "investor_owner_ratio": 70.0,
            "offplan_secondary_dominance": 90.0,
            "str_concentration": 8.0,
        },
    },

    "dubai_creek": {
        "project_name": 'Dubai Creek Harbour',
        "country": 'UAE',
        "city": 'Dubai',
        "price_range": 'AED 1.2M – AED 15M',
        "project_stage": 'Under Construction',
        "ownership": 'freehold',
        "project_type": 'managed',
        "highlight": "Emaar's massive waterfront masterplan offering strong rental yields",
        "description": 'Dubai Creek Harbour is a major master-planned community by Emaar Properties in the Ras Al Khor area. This emerging mixed-use development offers residents access to Creek Marina, Creek Beach, and the Ras Al Khor Wildlife Sanctuary.',
        "tags": ['Emaar brand', 'Waterfront', '6.5% rental yield', 'UAE Golden Visa'],

        "raw_variables": {
            "micro_market_stage": 75.0,
            "rental_absorption_velocity": 76.67,
            "days_on_market": 19.44,
            "occupancy_vacancy_rate": 40.0,
            "resale_velocity": 25.0,
            "safety_crime_index": 83.9,
            "air_quality_index": 34.33,
            "healthcare_access": 75.0,
            "school_quality": 75.0,
            "beach_coastal_access": 100.0,
            "population_growth_rate": 34.4,
            "expat_concentration": 100.0,
            "active_unsold_inventory": 37.5,
            "immediate_pipeline_risk": 100.0,
            "pct_projects_delivered": 90.0,
            "average_delay_duration": 10.42,
            "completion_consistency": 20.83,
            "debt_cash_position": 5.5,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 80.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 13.64,
            "flipping_frequency": 66.67,
            "projected_rental_yield": 50.0,
            "infrastructure_proximity": 50.0,
            "comp_capital_appreciation": 69.92,
            "comp_rental_yields": 50.0,
            "comp_occupancy_rate": 76.0,
            "investor_owner_ratio": 75.0,
            "offplan_secondary_dominance": 65.0,
            "str_concentration": 72.0,
        },
    },

    "greencrest": {
        "project_name": 'Greencrest at Dubai Hills Estate',
        "country": 'UAE',
        "city": 'Dubai',
        "price_range": 'AED 1.57M – AED 3.89M',
        "project_stage": 'Under Construction',
        "ownership": 'freehold',
        "project_type": 'apartment',
        "highlight": 'Emaar luxury residences in Dubai Hills with 6.5% yield and UAE Golden Visa',
        "description": "Greencrest at Dubai Hills Estate is an Emaar Properties development within the master-planned Dubai Hills community. The project sits adjacent to King's College Hospital London Dubai, GEMS International School, and Dubai Hills Mall.",
        "tags": ['6.5% rental yield', 'UAE Golden Visa', "King's College Hospital nearby", 'Emaar brand', '0% capital gains tax'],

        "raw_variables": {
            "micro_market_stage": 100.0,
            "rental_absorption_velocity": 23.33,
            "days_on_market": 13.89,
            "occupancy_vacancy_rate": 16.67,
            "resale_velocity": 16.67,
            "safety_crime_index": 83.9,
            "air_quality_index": 34.33,
            "healthcare_access": 100.0,
            "school_quality": 92.0,
            "beach_coastal_access": 50.0,
            "population_growth_rate": 34.4,
            "expat_concentration": 100.0,
            "active_unsold_inventory": 12.5,
            "immediate_pipeline_risk": 33.33,
            "pct_projects_delivered": 90.0,
            "average_delay_duration": 10.42,
            "completion_consistency": 20.83,
            "debt_cash_position": 5.5,
            "stalled_projects_count": 0.0,
            "escrow_quality": 100.0,
            "presales_pct_achieved": 90.0,
            "construction_quality": 100.0,
            "litigation_history": 0.0,
            "average_exit_velocity": 4.55,
            "flipping_frequency": 26.67,
            "projected_rental_yield": 57.5,
            "infrastructure_proximity": 100.0,
            "comp_capital_appreciation": 76.8,
            "comp_rental_yields": 57.5,
            "comp_occupancy_rate": 90.0,
            "investor_owner_ratio": 40.0,
            "offplan_secondary_dominance": 40.0,
            "str_concentration": 24.0,
        },
    },

}


def get_projects_by_cities(city_list: list) -> dict:
    """Return only projects whose city is in city_list."""
    return {k: v for k, v in PROJECTS.items() if v["city"] in city_list}


def get_projects_by_country(country: str) -> dict:
    """Return only projects for a specific country."""
    return {k: v for k, v in PROJECTS.items() if v["country"] == country}


def list_determinant_keys() -> list:
    """Return the canonical list of raw variable keys in bucket order."""
    return [
        "micro_market_stage", "rental_absorption_velocity", "resale_velocity", "days_on_market", "occupancy_vacancy_rate",
        "safety_crime_index", "healthcare_access", "school_quality", "air_quality_index", "beach_coastal_access",
        "population_growth_rate", "expat_concentration",
        "immediate_pipeline_risk", "active_unsold_inventory",
        "average_delay_duration", "pct_projects_delivered", "completion_consistency",
        "escrow_quality", "debt_cash_position", "stalled_projects_count", "presales_pct_achieved",
        "comp_capital_appreciation", "comp_rental_yields", "comp_occupancy_rate",
        "projected_rental_yield", "construction_quality", "litigation_history", "infrastructure_proximity",
        "str_concentration", "investor_owner_ratio", "offplan_secondary_dominance",
        "average_exit_velocity", "flipping_frequency",
    ]
