# PORTUGAL PROPERTY INVESTMENT ENGINE — DETERMINANT SCORES
# Updated: June 2026
# Source: project_scores.xlsx — Database for Engine
# Scores 0-100 magnitude. Engine handles inversion.

projects_data = {

    "the_lisboans": {
        "project_name": 'The Lisboans',
        "developer": 'Oxy Capital',
        "city": 'Lisbon',
        "country": 'Portugal',
        "area": 'Alfama / Baixa-Chiado',

        "raw_variables": {
            "micro_market_stage": 100,
            "rental_absorption_velocity": 70,
            "days_on_market": 17.6,
            "occupancy_vacancy_rate": 48,
            "resale_velocity": 70,
            "safety_crime_index": 70,
            "air_quality_index": 70,
            "healthcare_access": 70,
            "school_quality": 70,
            "beach_coastal_access": 70,
            "population_growth_rate": 4.7,
            "expat_concentration": 30,
            "active_unsold_inventory": 2,
            "immediate_pipeline_risk": 2,
            "pct_projects_delivered": 100,
            "average_delay_duration": 100,
            "completion_consistency": 100,
            "debt_cash_position": 70,
            "stalled_projects_count": 70,
            "escrow_quality": 70,
            "presales_pct_achieved": 100,
            "construction_quality": 100,
            "litigation_history": 100,
            "average_exit_velocity": 87.5,
            "flipping_frequency": 5,
            "projected_rental_yield": 60,
            "infrastructure_proximity": 100,
            "comp_capital_appreciation": 67.5,
            "comp_rental_yields": 30,
            "comp_occupancy_rate": 88,
            "investor_owner_ratio": 30,
            "offplan_secondary_dominance": 0,
            "str_concentration": 100,
        },
    },

    "palmares": {
        "project_name": 'Palmares Ocean Living & Golf Resort',
        "developer": 'Oxy Capital (actual developer: Arrow Global / ex-Kronos Homes)',
        "city": 'Lagos / Algarve',
        "country": 'Portugal',
        "area": 'Meia Praia, Lagos, Algarve',

        "raw_variables": {
            "micro_market_stage": 100,
            "rental_absorption_velocity": 70,
            "days_on_market": 17.6,
            "occupancy_vacancy_rate": 40,
            "resale_velocity": 70,
            "safety_crime_index": 70,
            "air_quality_index": 70,
            "healthcare_access": 70,
            "school_quality": 70,
            "beach_coastal_access": 100,
            "population_growth_rate": 8,
            "expat_concentration": 35,
            "active_unsold_inventory": 15,
            "immediate_pipeline_risk": 10,
            "pct_projects_delivered": 95,
            "average_delay_duration": 90,
            "completion_consistency": 92.5,
            "debt_cash_position": 70,
            "stalled_projects_count": 70,
            "escrow_quality": 70,
            "presales_pct_achieved": 70,
            "construction_quality": 100,
            "litigation_history": 100,
            "average_exit_velocity": 80,
            "flipping_frequency": 10,
            "projected_rental_yield": 55,
            "infrastructure_proximity": 75,
            "comp_capital_appreciation": 60,
            "comp_rental_yields": 27.5,
            "comp_occupancy_rate": 90,
            "investor_owner_ratio": 60,
            "offplan_secondary_dominance": 50,
            "str_concentration": 40,
        },
    },

    "amoreiras_prime": {
        "project_name": 'Amoreiras Prime Residences',
        "developer": 'Vanguard Properties',
        "city": 'Lisbon',
        "country": 'Portugal',
        "area": 'Amoreiras, Lisbon',

        "raw_variables": {
            "micro_market_stage": 100,
            "rental_absorption_velocity": 70,
            "days_on_market": 17.6,
            "occupancy_vacancy_rate": 20,
            "resale_velocity": 70,
            "safety_crime_index": 70,
            "air_quality_index": 70,
            "healthcare_access": 70,
            "school_quality": 70,
            "beach_coastal_access": 70,
            "population_growth_rate": 4.7,
            "expat_concentration": 20,
            "active_unsold_inventory": 5,
            "immediate_pipeline_risk": 5,
            "pct_projects_delivered": 80,
            "average_delay_duration": 80,
            "completion_consistency": 90,
            "debt_cash_position": 70,
            "stalled_projects_count": 70,
            "escrow_quality": 70,
            "presales_pct_achieved": 90,
            "construction_quality": 80,
            "litigation_history": 100,
            "average_exit_velocity": 85,
            "flipping_frequency": 15,
            "projected_rental_yield": 45,
            "infrastructure_proximity": 100,
            "comp_capital_appreciation": 52.5,
            "comp_rental_yields": 22.5,
            "comp_occupancy_rate": 95,
            "investor_owner_ratio": 40,
            "offplan_secondary_dominance": 20,
            "str_concentration": 15,
        },
    },

    "infante_residences": {
        "project_name": 'Infante Residences',
        "developer": 'Vanguard Properties',
        "city": 'Lisbon',
        "country": 'Portugal',
        "area": 'Estrela / Avenida Infante Santo, Lisbon',

        "raw_variables": {
            "micro_market_stage": 75,
            "rental_absorption_velocity": 70,
            "days_on_market": 17.6,
            "occupancy_vacancy_rate": 32,
            "resale_velocity": 70,
            "safety_crime_index": 70,
            "air_quality_index": 70,
            "healthcare_access": 70,
            "school_quality": 70,
            "beach_coastal_access": 70,
            "population_growth_rate": 4.7,
            "expat_concentration": 25,
            "active_unsold_inventory": 10,
            "immediate_pipeline_risk": 15,
            "pct_projects_delivered": 70,
            "average_delay_duration": 70,
            "completion_consistency": 85,
            "debt_cash_position": 70,
            "stalled_projects_count": 70,
            "escrow_quality": 70,
            "presales_pct_achieved": 80,
            "construction_quality": 80,
            "litigation_history": 100,
            "average_exit_velocity": 82.5,
            "flipping_frequency": 20,
            "projected_rental_yield": 50,
            "infrastructure_proximity": 100,
            "comp_capital_appreciation": 56,
            "comp_rental_yields": 25,
            "comp_occupancy_rate": 92,
            "investor_owner_ratio": 70,
            "offplan_secondary_dominance": 85,
            "str_concentration": 25,
        },
    },

}
