# THAILAND PROPERTY INVESTMENT ENGINE — DETERMINANT SCORES
# Updated: June 2026
# Source: project_scores.xlsx — Database for Engine
# Scores 0-100 magnitude. Engine handles inversion.

THAILAND_RESEARCH = {

    "laguna_lakelands": {
        "project_name": 'Laguna Lakelands',
        "developer": 'Banyan Group (Banyan Tree Holdings Ltd, SGX: B58)',
        "city": 'Phuket',
        "country": 'Thailand',
        "area": 'Bang Tao / Laguna Phuket, Thalang District',

        "raw_variables": {
            "micro_market_stage": 75,
            "rental_absorption_velocity": 20,
            "days_on_market": 22.22,
            "occupancy_vacancy_rate": 46.67,
            "resale_velocity": 27.78,
            "safety_crime_index": 32.5,
            "air_quality_index": 30,
            "healthcare_access": 50,
            "school_quality": 75,
            "beach_coastal_access": 75,
            "population_growth_rate": 45,
            "expat_concentration": 66.67,
            "active_unsold_inventory": 50,
            "immediate_pipeline_risk": 73.33,
            "pct_projects_delivered": 96,
            "average_delay_duration": 4.17,
            "completion_consistency": 8.33,
            "debt_cash_position": 22.5,
            "stalled_projects_count": 0,
            "escrow_quality": 100,
            "presales_pct_achieved": 75,
            "construction_quality": 88,
            "litigation_history": 0,
            "average_exit_velocity": 18.18,
            "flipping_frequency": 50,
            "projected_rental_yield": 35,
            "infrastructure_proximity": 100,
            "comp_capital_appreciation": 48,
            "comp_rental_yields": 35,
            "comp_occupancy_rate": 72,
            "investor_owner_ratio": 75,
            "offplan_secondary_dominance": 90,
            "str_concentration": 48,
        },
    },

    "hythe_by_botanica": {
        "project_name": 'HYTHE by Botanica',
        "developer": 'Botanica Luxury Phuket Co., Ltd. (AAP Architecture Properties & Development)',
        "city": 'Phuket',
        "country": 'Thailand',
        "area": 'Cherngtalay (Choeng Thale), Bang Tao, Thalang District',

        "raw_variables": {
            "micro_market_stage": 75,
            "rental_absorption_velocity": 13.33,
            "days_on_market": 19.44,
            "occupancy_vacancy_rate": 50,
            "resale_velocity": 25,
            "safety_crime_index": 32.5,
            "air_quality_index": 30,
            "healthcare_access": 50,
            "school_quality": 75,
            "beach_coastal_access": 50,
            "population_growth_rate": 45,
            "expat_concentration": 72.22,
            "active_unsold_inventory": 62.5,
            "immediate_pipeline_risk": 93.33,
            "pct_projects_delivered": 94,
            "average_delay_duration": 4.17,
            "completion_consistency": 8.33,
            "debt_cash_position": 30,
            "stalled_projects_count": 0,
            "escrow_quality": 100,
            "presales_pct_achieved": 80,
            "construction_quality": 85,
            "litigation_history": 0,
            "average_exit_velocity": 13.64,
            "flipping_frequency": 60,
            "projected_rental_yield": 40,
            "infrastructure_proximity": 50,
            "comp_capital_appreciation": 54,
            "comp_rental_yields": 40,
            "comp_occupancy_rate": 70,
            "investor_owner_ratio": 80,
            "offplan_secondary_dominance": 85,
            "str_concentration": 80,
        },
    },

    "noble_ploenchit": {
        "project_name": 'Noble Ploenchit',
        "developer": 'Noble Development Public Company Limited (SET: NOBLE)',
        "city": 'Bangkok',
        "country": 'Thailand',
        "area": 'Phloen Chit Road, Lumphini, Pathum Wan District',

        "raw_variables": {
            "micro_market_stage": 100,
            "rental_absorption_velocity": 43.33,
            "days_on_market": 25,
            "occupancy_vacancy_rate": 33.33,
            "resale_velocity": 33.33,
            "safety_crime_index": 41.2,
            "air_quality_index": 46.67,
            "healthcare_access": 75,
            "school_quality": 85,
            "beach_coastal_access": 0,
            "population_growth_rate": 31,
            "expat_concentration": 50,
            "active_unsold_inventory": 37.5,
            "immediate_pipeline_risk": 40,
            "pct_projects_delivered": 92,
            "average_delay_duration": 8.33,
            "completion_consistency": 16.67,
            "debt_cash_position": 60,
            "stalled_projects_count": 0,
            "escrow_quality": 100,
            "presales_pct_achieved": 95,
            "construction_quality": 80,
            "litigation_history": 0,
            "average_exit_velocity": 22.73,
            "flipping_frequency": 40,
            "projected_rental_yield": 25,
            "infrastructure_proximity": 100,
            "comp_capital_appreciation": 36.8,
            "comp_rental_yields": 25,
            "comp_occupancy_rate": 80,
            "investor_owner_ratio": 60,
            "offplan_secondary_dominance": 15,
            "str_concentration": 60,
        },
    },

    "monument_thong_lo": {
        "project_name": 'The Monument Thong Lo',
        "developer": 'Sansiri Public Company Limited (SET: SIRI)',
        "city": 'Bangkok',
        "country": 'Thailand',
        "area": 'Thong Lo (Sukhumvit Soi 55), Watthana District',

        "raw_variables": {
            "micro_market_stage": 100,
            "rental_absorption_velocity": 26.67,
            "days_on_market": 30.56,
            "occupancy_vacancy_rate": 40,
            "resale_velocity": 38.89,
            "safety_crime_index": 41.2,
            "air_quality_index": 46.67,
            "healthcare_access": 75,
            "school_quality": 90,
            "beach_coastal_access": 0,
            "population_growth_rate": 31,
            "expat_concentration": 61.11,
            "active_unsold_inventory": 25,
            "immediate_pipeline_risk": 50,
            "pct_projects_delivered": 95,
            "average_delay_duration": 6.25,
            "completion_consistency": 12.5,
            "debt_cash_position": 55,
            "stalled_projects_count": 0,
            "escrow_quality": 100,
            "presales_pct_achieved": 100,
            "construction_quality": 80,
            "litigation_history": 0,
            "average_exit_velocity": 27.27,
            "flipping_frequency": 26.67,
            "projected_rental_yield": 20,
            "infrastructure_proximity": 100,
            "comp_capital_appreciation": 42,
            "comp_rental_yields": 20,
            "comp_occupancy_rate": 76,
            "investor_owner_ratio": 50,
            "offplan_secondary_dominance": 5,
            "str_concentration": 32,
        },
    },

}
