# GREECE PROPERTY INVESTMENT ENGINE — DETERMINANT SCORES
# Updated: June 2026
# Source: project_scores.xlsx — Database for Engine
# Scores 0-100 magnitude. Engine handles inversion.

projects_data = {

    "luxeasy_thessaloniki": {
        "project_name": 'LUX&EASY Thessaloniki',
        "developer": 'NOVA CONSTRUCTIONS S.A.',
        "city": 'Thessaloniki',
        "country": 'Greece',
        "area": 'Thessaloniki Metropolitan Area',

        "raw_variables": {
            "micro_market_stage": 75,
            "rental_absorption_velocity": 95,
            "days_on_market": 19,
            "occupancy_vacancy_rate": 42,
            "resale_velocity": 55,
            "safety_crime_index": 53.8,
            "air_quality_index": 55,
            "healthcare_access": 85,
            "school_quality": 85,
            "beach_coastal_access": 100,
            "population_growth_rate": 4,
            "expat_concentration": 10,
            "active_unsold_inventory": 10,
            "immediate_pipeline_risk": 15,
            "pct_projects_delivered": 85,
            "average_delay_duration": 70,
            "completion_consistency": 85,
            "debt_cash_position": 65,
            "stalled_projects_count": 0,
            "escrow_quality": 100,
            "presales_pct_achieved": 75,
            "construction_quality": 90,
            "litigation_history": 100,
            "average_exit_velocity": 82.5,
            "flipping_frequency": 20,
            "projected_rental_yield": 60,
            "infrastructure_proximity": 75,
            "comp_capital_appreciation": 48,
            "comp_rental_yields": 30,
            "comp_occupancy_rate": 92,
            "investor_owner_ratio": 50,
            "offplan_secondary_dominance": 75,
            "str_concentration": 45,
        },
    },

    "one_athens": {
        "project_name": 'One Athens',
        "developer": 'DIMAND S.A.',
        "city": 'Athens',
        "country": 'Greece',
        "area": 'Kolonaki / Athens City Centre',

        "raw_variables": {
            "micro_market_stage": 100,
            "rental_absorption_velocity": 90,
            "days_on_market": 31.6,
            "occupancy_vacancy_rate": 29,
            "resale_velocity": 90,
            "safety_crime_index": 55.2,
            "air_quality_index": 48,
            "healthcare_access": 92,
            "school_quality": 92,
            "beach_coastal_access": 70,
            "population_growth_rate": 0,
            "expat_concentration": 10,
            "active_unsold_inventory": 5,
            "immediate_pipeline_risk": 5,
            "pct_projects_delivered": 95,
            "average_delay_duration": 90,
            "completion_consistency": 95,
            "debt_cash_position": 60,
            "stalled_projects_count": 0,
            "escrow_quality": 100,
            "presales_pct_achieved": 100,
            "construction_quality": 100,
            "litigation_history": 100,
            "average_exit_velocity": 80,
            "flipping_frequency": 10,
            "projected_rental_yield": 40,
            "infrastructure_proximity": 100,
            "comp_capital_appreciation": 31,
            "comp_rental_yields": 20,
            "comp_occupancy_rate": 94,
            "investor_owner_ratio": 40,
            "offplan_secondary_dominance": 0,
            "str_concentration": 20,
        },
    },

    "ellinikon_marina_residences": {
        "project_name": 'The Ellinikon – Marina Residences',
        "developer": 'LAMDA Development S.A.',
        "city": 'Athens',
        "country": 'Greece',
        "area": 'Elliniko / Agios Kosmas Marina, Athens Riviera',

        "raw_variables": {
            "micro_market_stage": 75,
            "rental_absorption_velocity": 85,
            "days_on_market": 21.8,
            "occupancy_vacancy_rate": 25,
            "resale_velocity": 60,
            "safety_crime_index": 58.5,
            "air_quality_index": 52,
            "healthcare_access": 88,
            "school_quality": 88,
            "beach_coastal_access": 100,
            "population_growth_rate": 5,
            "expat_concentration": 15,
            "active_unsold_inventory": 15,
            "immediate_pipeline_risk": 10,
            "pct_projects_delivered": 80,
            "average_delay_duration": 80,
            "completion_consistency": 90,
            "debt_cash_position": 40,
            "stalled_projects_count": 0,
            "escrow_quality": 100,
            "presales_pct_achieved": 81,
            "construction_quality": 100,
            "litigation_history": 100,
            "average_exit_velocity": 85,
            "flipping_frequency": 15,
            "projected_rental_yield": 45,
            "infrastructure_proximity": 100,
            "comp_capital_appreciation": 57.5,
            "comp_rental_yields": 22.5,
            "comp_occupancy_rate": 90,
            "investor_owner_ratio": 60,
            "offplan_secondary_dominance": 81,
            "str_concentration": 35,
        },
    },

}
