# UAE PROPERTY INVESTMENT ENGINE — DETERMINANT SCORES
# Updated: June 2026
# Source: project_scores.xlsx — Database for Engine
# Scores 0-100 magnitude. Engine handles inversion.

UAE_PROPERTIES_RAW = {

    "greencrest": {
        "project_name": 'Greencrest at Dubai Hills Estate',
        "developer": 'Emaar Properties',
        "city": 'Dubai',
        "country": 'UAE',
        "area": 'Dubai Hills Estate, MBR City',

        "raw_variables": {
            "micro_market_stage": 100,
            "rental_absorption_velocity": 23.33,
            "days_on_market": 13.89,
            "occupancy_vacancy_rate": 16.67,
            "resale_velocity": 16.67,
            "safety_crime_index": 16.1,
            "air_quality_index": 43,
            "healthcare_access": 100,
            "school_quality": 92,
            "beach_coastal_access": 50,
            "population_growth_rate": 34.4,
            "expat_concentration": 100,
            "active_unsold_inventory": 12.5,
            "immediate_pipeline_risk": 33.33,
            "pct_projects_delivered": 90,
            "average_delay_duration": 10.42,
            "completion_consistency": 20.83,
            "debt_cash_position": 15,
            "stalled_projects_count": 0,
            "escrow_quality": 100,
            "presales_pct_achieved": 90,
            "construction_quality": 100,
            "litigation_history": 0,
            "average_exit_velocity": 4.55,
            "flipping_frequency": 26.67,
            "projected_rental_yield": 57.5,
            "infrastructure_proximity": 100,
            "comp_capital_appreciation": 76.8,
            "comp_rental_yields": 57.5,
            "comp_occupancy_rate": 90,
            "investor_owner_ratio": 40,
            "offplan_secondary_dominance": 40,
            "str_concentration": 24,
        },
    },

    "sobha_hartland": {
        "project_name": 'Sobha Hartland',
        "developer": 'Sobha Realty',
        "city": 'Dubai',
        "country": 'UAE',
        "area": 'Mohammed Bin Rashid City (MBR City), Dubai',

        "raw_variables": {
            "micro_market_stage": 75,
            "rental_absorption_velocity": 11,
            "resale_velocity": 10.7,
            "days_on_market": 16.2,
            "occupancy_vacancy_rate": 74,
            "safety_crime_index": 83.9,
            "healthcare_access": 65,
            "school_quality": 90,
            "air_quality_index": 52.5,
            "beach_coastal_access": 0,
            "population_growth_rate": 66,
            "expat_concentration": 90,
            "immediate_pipeline_risk": 54,
            "active_unsold_inventory": 32.5,
            "average_delay_duration": 6.3,
            "pct_projects_delivered": 92,
            "completion_consistency": 100,
            "escrow_quality": 100,
            "debt_cash_position": 68,
            "stalled_projects_count": 0,
            "presales_pct_achieved": 88,
            "comp_capital_appreciation": 45,
            "comp_rental_yields": 50,
            "comp_occupancy_rate": 74,
            "str_concentration": 36.7,
            "investor_owner_ratio": 67,
            "offplan_secondary_dominance": 70,
        },
    },

    "burj_binghatti": {
        "project_name": 'Burj Binghatti Jacob & Co Residences',
        "developer": 'Binghatti Developers',
        "city": 'Dubai',
        "country": 'UAE',
        "area": 'Business Bay, Dubai',

        "raw_variables": {
            "micro_market_stage": 100,
            "rental_absorption_velocity": 83.33,
            "days_on_market": 16.67,
            "occupancy_vacancy_rate": 26.67,
            "resale_velocity": 19.44,
            "safety_crime_index": 16.1,
            "air_quality_index": 43,
            "healthcare_access": 100,
            "school_quality": 80,
            "beach_coastal_access": 50,
            "population_growth_rate": 34.4,
            "expat_concentration": 100,
            "active_unsold_inventory": 50,
            "immediate_pipeline_risk": 83.33,
            "pct_projects_delivered": 85,
            "average_delay_duration": 12.5,
            "completion_consistency": 25,
            "debt_cash_position": 40,
            "stalled_projects_count": 0,
            "escrow_quality": 100,
            "presales_pct_achieved": 85,
            "construction_quality": 95,
            "litigation_history": 0,
            "average_exit_velocity": 9.09,
            "flipping_frequency": 83.33,
            "projected_rental_yield": 42,
            "infrastructure_proximity": 100,
            "comp_capital_appreciation": 66,
            "comp_rental_yields": 42,
            "comp_occupancy_rate": 84,
            "investor_owner_ratio": 85,
            "offplan_secondary_dominance": 80,
            "str_concentration": 88,
        },
    },

    "damac_islands": {
        "project_name": 'DAMAC Islands',
        "developer": 'DAMAC Properties',
        "city": 'Dubai',
        "country": 'UAE',
        "area": 'Dubailand, Dubai',

        "raw_variables": {
            "micro_market_stage": 50,
            "rental_absorption_velocity": 16.67,
            "days_on_market": 22.22,
            "occupancy_vacancy_rate": 33.33,
            "resale_velocity": 27.78,
            "safety_crime_index": 16.1,
            "air_quality_index": 43,
            "healthcare_access": 50,
            "school_quality": 70,
            "beach_coastal_access": 50,
            "population_growth_rate": 34.4,
            "expat_concentration": 100,
            "active_unsold_inventory": 87.5,
            "immediate_pipeline_risk": 100,
            "pct_projects_delivered": 88,
            "average_delay_duration": 16.67,
            "completion_consistency": 33.33,
            "debt_cash_position": 25,
            "stalled_projects_count": 0,
            "escrow_quality": 100,
            "presales_pct_achieved": 90,
            "construction_quality": 80,
            "litigation_history": 0,
            "average_exit_velocity": 22.73,
            "flipping_frequency": 100,
            "projected_rental_yield": 55,
            "infrastructure_proximity": 50,
            "comp_capital_appreciation": 80,
            "comp_rental_yields": 55,
            "comp_occupancy_rate": 80,
            "investor_owner_ratio": 70,
            "offplan_secondary_dominance": 90,
            "str_concentration": 8,
        },
    },

    "dubai_creek": {
        "project_name": 'Dubai Creek Harbour',
        "developer": 'Emaar Properties',
        "city": 'Dubai',
        "country": 'UAE',
        "area": 'Dubai Creek Harbour (Ras Al Khor), Dubai',

        "raw_variables": {
            "micro_market_stage": 75,
            "rental_absorption_velocity": 76.67,
            "days_on_market": 19.44,
            "occupancy_vacancy_rate": 40,
            "resale_velocity": 25,
            "safety_crime_index": 16.1,
            "air_quality_index": 43,
            "healthcare_access": 75,
            "school_quality": 75,
            "beach_coastal_access": 100,
            "population_growth_rate": 34.4,
            "expat_concentration": 100,
            "active_unsold_inventory": 37.5,
            "immediate_pipeline_risk": 100,
            "pct_projects_delivered": 90,
            "average_delay_duration": 10.42,
            "completion_consistency": 20.83,
            "debt_cash_position": 15,
            "stalled_projects_count": 0,
            "escrow_quality": 100,
            "presales_pct_achieved": 80,
            "construction_quality": 100,
            "litigation_history": 0,
            "average_exit_velocity": 13.64,
            "flipping_frequency": 66.67,
            "projected_rental_yield": 50,
            "infrastructure_proximity": 50,
            "comp_capital_appreciation": 69.92,
            "comp_rental_yields": 50,
            "comp_occupancy_rate": 76,
            "investor_owner_ratio": 75,
            "offplan_secondary_dominance": 65,
            "str_concentration": 72,
        },
    },

}
